### ISSUE TITLE
Issue with making it work

### ISSUE THREAD

**Issue by gjesguerra** [vsco/keys#1]
Hi,

I am kind of confused on how to make it work, I have followed the instructions to download the For Mac version and install it on my Macbook. I have also added the vscokeys to the plug-in manager. 

My question is, how do I see the interface for editing the shortcuts as seen in the product video demo? And I am not seeing the icon for vscokeys in LR.

Do I need to do something else?

Any help would be appreciated. 

Thank you.

**Comment by StefanKrauth** [comment]
I don't know why app launcher is not working, but typing this into the Terminal brings the icon up and I can activate it in Lightroom with ESC:

`/Applications/vscokeys/VSCOKeys.app/Contents/MacOS/VSCOKeys`

However, clicking on settings does not launch a settings dialog.

**Comment by parkr** [comment]
Hey, @gjesguerra! Thanks for downloading Keys.

> My question is, how do I see the interface for editing the shortcuts as seen in the product video demo? And I am not seeing the icon for vscokeys in LR.

The interface for editing shortcuts (the layout manager) is still available for current customers of VSCO Keys, the predecessor to Keys. While we are interested in open-sourcing and making available this layout manager, we can't make any promises about if and when it might be available. For now, see our instructions here: https://github.com/vsco/keys#creating-your-own-layout-file

**Comment by parkr** [comment]
> However, clicking on settings does not launch a settings dialog.

@StefanKrauth, do you have a screenshot you could share with me?

**Comment by StefanKrauth** [comment]
@parkr Okay, that makes sense. We should remove the settings button then or just use it to open the right layout folder.

This is how it works for me right now:
https://www.youtube.com/watch?v=gh0T_rXZS2o

**Comment by parkr** [comment]
@StefanKrauth Thanks for the video! That is very helpful. Would you mind opening a new ticket to change the behaviour of "Settings"?

**Comment by StefanKrauth** [comment]
@parkr done.

But why have you closed this issue? There is still the problem that vsco keys can only be launched from the command line and not via the .app file. I think this is what this issue is about.

**Comment by benny-danny** [comment]
Are you guys using osx or windows? If it is osx, do you have authorized vsco keys in the system preferences -> security & privacy -> privacy tab ?

**Comment by StefanKrauth** [comment]
@benny-danny Nope, that's it. Thank you! Now it is starting as expected.
